---
- hosts: web-server1
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: true
    - name: Install PHP and PHP Apache module
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - libapache2-mod-php
    - name: Ensure Apache is started
      systemd:
        name: apache2
        state: started
        enabled: true

    - name: Wait for 15 seconds
      wait_for:
        timeout: 15

- hosts: web-server2
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: true
    - name: Install PHP and PHP Apache module
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - libapache2-mod-php
    - name: Ensure Apache is started
      systemd:
        name: apache2
        state: started
        enabled: true

- hosts: web-server1
  become: yes
  tasks:
    - name: Synkronisera mappen ./wwwroot-server1 på värden med /var/www/html på web-server1
      synchronize:
        src: ./wwwroot-server1/  # Lokala mappen för web-server1
        dest: /var/www/html/  # Destination på web-server1
        rsync_opts:
          - "--delete"


- hosts: web-server2
  become: yes
  tasks:
    - name: Synkronisera mappen ./wwwroot-server2 på värden med /var/www/html på web-server2
      synchronize:
        src: ./wwwroot-server2/  # Lokala mappen för web-server2
        dest: /var/www/html/  # Destination på web-server2
        rsync_opts:
          - "--delete"

    - name: Wait for 15 seconds
      wait_for:
        timeout: 15

- hosts: database-server
  become: true
  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
        update_cache: true

    - name: Ensure MySQL is started
      systemd:
        name: mysql
        state: started
        enabled: true


    - name: Wait for 10 seconds
      wait_for:
        timeout: 10

- hosts: load-balancer
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: true
    - name: Ensure Nginx is started
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: Wait for 10 seconds
      wait_for:
        timeout: 10


- hosts: load-balancer
  become: yes
  tasks:
    - name: Kopiera bash-script till VM
      copy:
        src: ./setup_loadbalancer.sh  # Lokala vägen till ditt bash-script
        dest: /home/setup_loadbalancer.sh  # Destinationen på VM:n
        mode: '0755'  # Gör skriptet exekverbart

    - name: Convert DOS line endings to UNIX
      shell: sed -i 's/\r$//' /home/setup_loadbalancer.sh

    - name: Kör bash-scriptet på VM
      shell: "/home/setup_loadbalancer.sh"  # Kör skriptet
