---
- hosts: webservers
  become: yes
  gather_facts: yes
  tasks:
    - name: Ensure PermitRootLogin is set to yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin yes'
        state: present
      notify: Restart SSH

    - name: Ensure PasswordAuthentication is set to yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present
      notify: Restart SSH

    - name: Install Apache2
      apt:
        name: apache2
        state: present

  handlers:
    - name: Restart SSH
      systemd:
        name: ssh
        state: restarted
