---
- name: Install and configure MySQL
  hosts: database-server
  become: yes
  vars_files:
    - ../credentials/vault.yml
  vars:
    mysql_root_password: '1134a'
    mysql_user: 'test_user'
    mysql_user_password: '1134a'
    mysql_database: 'test_database'

  tasks:
    - name: Install MySQL server and pip
      apt:
        name:
          - python3-pip
          - mysql-server
        state: present
      tags: [mysql, install]

    - name: Create MySQL credentials file
      copy:
        dest: /root/.my.cnf
        content: |
          [client]
          user=root
          password={{ mysql_root_password }}
        mode: '0600'
      tags: [mysql, configure]

    - name: Update MySQL root password
      mysql_db:
        name: mysql
        state: import
        target: ../update_root_password.sql
      tags: [mysql, configure]

    - name: Create MySQL database
      mysql_db:
        name: "{{ mysql_database }}"
        state: present
      tags: [mysql, database]

    - name: Create MySQL user with privileges
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_user_password }}"
        priv: "{{ mysql_database }}.*:ALL"
        host: "%"
        state: present
        login_password: "{{ mysql_root_password }}"
        login_user: root
        login_host: localhost
      tags: [mysql, user]
