---
- name: Set up logging and log rotation for critical system and security events
  hosts: web-server1, web-server2, database-server, load-balancer
  become: yes
  tasks:
    # 1. Install rsyslog and logrotate if not already installed
    - name: Ensure rsyslog is installed
      ansible.builtin.apt:
        name: rsyslog
        state: present

    - name: Ensure logrotate is installed
      ansible.builtin.apt:
        name: logrotate
        state: present

    # 2. Configure rsyslog for critical and security logging
    - name: Configure rsyslog for critical and security logging
      ansible.builtin.copy:
        dest: /etc/rsyslog.d/50-default.conf
        content: |
          auth,authpriv.*                        /var/log/auth.log
          kern.*                                 /var/log/kern.log
          cron.*                                 /var/log/cron.log
          *.emerg                                :omusrmsg:*
          *.crit                                 /var/log/critical.log
      notify: Restart rsyslog

    # 3. Create a logrotate configuration
    - name: Configure logrotate for critical logs
      ansible.builtin.copy:
        dest: /etc/logrotate.d/system-logs
        content: |
          /var/log/auth.log
          /var/log/kern.log
          /var/log/cron.log
          /var/log/critical.log {
            daily
            rotate 7
            compress
            missingok
            notifempty
            create 640 syslog adm
            sharedscripts
            postrotate
                /usr/lib/rsyslog/rsyslog-rotate
                systemctl reload rsyslog > /dev/null 2>&1 || true
            endscript
          }

    # 4. Fix permissions for /var/log directory
    - name: Ensure /var/log has correct permissions
      ansible.builtin.file:
        path: /var/log
        owner: root
        group: root
        mode: '0755'

  handlers:
    - name: Restart rsyslog
      ansible.builtin.service:
        name: rsyslog
        state: restarted
