


- hosts: web-server1
  vars_files:
    - ../credentials/vault.yml  # Stig till din Vault-fil
  tasks:
    - name: Deploy PHP database config file
      template:
        src: ../config.php.j2
        dest: /var/www/html/config.php
        owner: www-data
        group: www-data
        mode: '0644'
      become: true
